# Groupby Core

*Author*: Yousef Al Zeer

In [ ]:
# Loading the data

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
insurance_url = "/content/drive/MyDrive/AXSOSACADEMY/01-Fundamentals/Week02/Data/insurance_mod.csv"

In [ ]:
import pandas as pd

df_insurance = pd.read_csv(insurance_url)

In [ ]:
# 1 - Average age

avg_age = df_insurance["age"].mean()
print(f"Average age of this data set is {avg_age:.2f}")

Average age of this data set is 39.21

In [ ]:
#2 Maximum age
max_age = df_insurance["age"].max()
max_age

64

In [ ]:
# 3 Min age
min_age = df_insurance["age"].min()
min_age

18

In [ ]:
# 4 average of charges

avg_charges = df_insurance['charges'].mean()
print(f" Average Charges :{avg_charges:.2f}")

 Average Charges :13270.41

In [ ]:
# 5 - average of charges grouped by sex

avg_charge_sex = df_insurance.groupby("sex")["charges"].mean().round(2)
avg_charge_sex

sex
female    12569.58
male      13956.73
Name: charges, dtype: float64

In [ ]:
# 6 - group by and smoker

group_sex_smoker = df_insurance.groupby("smoker")["charges"].mean().round(2)
group_sex_smoker

smoker
0     8434.26
1    32050.23
Name: charges, dtype: float64

In [ ]:
# 7 - avg charges by smoker and sex

avg_cahrges_smoker_sex = df_insurance.groupby(["sex" , "smoker"])["charges"].mean().round(2)
avg_cahrges_smoker_sex

sex     smoker
female  0          8762.31
        1         30678.98
male    0          8087.18
        1         33042.01
Name: charges, dtype: float64